version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "submodule"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
    exclude-paths:
      - "apps/docs/**"
      - "benchmarks/**"
      - "testdata/**"
    ignore:
      - dependency-name: "@tsgonest/cli-*"
