package codegen

import (
	"sort"
)

// GenerateHelpers generates the shared _tsgonest_helpers.js file content.
// This file contains serialization helpers and format regex constants
// that are shared across all companion files, avoiding code duplication.
func GenerateHelpers() string {
	e := NewEmitter()
	e.Line("// Auto-generated by tsgonest — do not edit")
	e.Blank()

	// __e: TsgonestValidationError — thrown by assert functions
	e.Block("export class __e extends Error")
	e.Block("constructor(errors)")
	e.Line("super(\"Validation failed: \" + errors.length + \" error(s)\");")
	e.Line("this.name = \"TsgonestValidationError\";")
	e.Line("this.errors = errors;")
	e.Line("this.status = 400;")
	e.EndBlock()
	e.EndBlock()
	e.Blank()

	// __s: fast string serializer
	e.Block("export function __s(s)")
	e.Line("for (var i = 0; i < s.length; i++) { var c = s.charCodeAt(i); if (c < 32 || c === 34 || c === 92) return JSON.stringify(s); }")
	e.Line("return '\"' + s + '\"';")
	e.EndBlock()

	// __sa: fast array serializer
	e.Block("export function __sa(a, f)")
	e.Line("var r = \"[\"; for (var i = 0; i < a.length; i++) { if (i) r += \",\"; r += f(a[i]); } return r + \"]\";")
	e.EndBlock()
	e.Blank()

	// Format regex constants
	names := make([]string, 0, len(formatRegexes))
	for name := range formatRegexes {
		if formatRegexes[name] == "" {
			continue // skip empty patterns (password, regex)
		}
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		pattern := formatRegexes[name]
		flags := formatFlags[name]
		constName := FormatConstName(name)
		if flags != "" {
			e.Line("export const %s = /%s/%s;", constName, pattern, flags)
		} else {
			e.Line("export const %s = /%s/;", constName, pattern)
		}
	}

	return e.String()
}

// GenerateHelpersTypes generates the _tsgonest_helpers.d.ts type declarations.
func GenerateHelpersTypes() string {
	e := NewEmitter()
	e.Line("// Auto-generated by tsgonest — do not edit")
	e.Blank()
	e.Line("export declare class __e extends Error { errors: { path: string; expected: string; received: string }[]; status: number; }")
	e.Line("export declare function __s(s: string): string;")
	e.Line("export declare function __sa(a: readonly unknown[], f: (v: unknown) => string): string;")

	names := make([]string, 0, len(formatRegexes))
	for name := range formatRegexes {
		if formatRegexes[name] == "" {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		e.Line("export declare const %s: RegExp;", FormatConstName(name))
	}

	return e.String()
}

// FormatConstName converts a format name like "date-time" to a JS constant name like "__fmt_date_time".
func FormatConstName(name string) string {
	result := "__fmt_"
	for _, c := range name {
		if c == '-' {
			result += "_"
		} else {
			result += string(c)
		}
	}
	return result
}
