/**
 * Migration report — structured tracking of all transforms, warnings, and TODOs.
 *
 * After migrate runs, this produces:
 *   1. Console summary (always)
 *   2. tsgonest-migrate-report.md file (when --apply is used)
 */

import { relative } from "path";
import { YELLOW, RESET } from "./colors.js";

export type Severity = "todo" | "warning" | "info";

export interface ReportItem {
  severity: Severity;
  file: string;
  line?: number;
  message: string;
  /** Category for grouping in the report. */
  category: "nestia" | "typia" | "class-validator" | "class-transformer" | "swagger" | "general";
}

export interface TransformStats {
  nestia: number;
  typia: number;
  classValidator: number;
  classTransformer: number;
  swagger: number;
  baseUrlRewrites: number;
}

export interface PackageJsonChanges {
  removedDeps: string[];
  addedDeps: string[];
  updatedScripts: string[];
  removedConfigFiles: string[];
}

export class MigrateReport {
  items: ReportItem[] = [];
  stats: TransformStats = {
    nestia: 0,
    typia: 0,
    classValidator: 0,
    classTransformer: 0,
    swagger: 0,
    baseUrlRewrites: 0,
  };
  filesChanged = new Set<string>();
  packageJsonChanges: PackageJsonChanges = {
    removedDeps: [],
    addedDeps: [],
    updatedScripts: [],
    removedConfigFiles: [],
  };
  /** Security schemes auto-detected from swagger decorators (e.g. @ApiBearerAuth). */
  detectedSecuritySchemes = new Map<string, Record<string, string>>();
  /** Whether tsgonest.config.ts was auto-generated. */
  configFileGenerated = false;
  /** Whether tsconfig.json was modified. */
  tsconfigModified = false;

  add(item: ReportItem): void {
    this.items.push(item);
  }

  todo(file: string, category: ReportItem["category"], message: string, line?: number): void {
    this.items.push({ severity: "todo", file, category, message, line });
  }

  warn(file: string, category: ReportItem["category"], message: string, line?: number): void {
    this.items.push({ severity: "warning", file, category, message, line });
  }

  info(file: string, category: ReportItem["category"], message: string, line?: number): void {
    this.items.push({ severity: "info", file, category, message, line });
  }

  get totalTransforms(): number {
    return (
      this.stats.nestia +
      this.stats.typia +
      this.stats.classValidator +
      this.stats.classTransformer +
      this.stats.swagger +
      this.stats.baseUrlRewrites
    );
  }

  get todos(): ReportItem[] {
    return this.items.filter((i) => i.severity === "todo");
  }

  get warnings(): ReportItem[] {
    return this.items.filter((i) => i.severity === "warning");
  }

  /** Print summary to console. */
  printSummary(cwd: string): void {
    const rel = (filePath: string) => relative(cwd, filePath);

    // Stats
    console.log(`\n  Transforms applied:`);
    if (this.stats.nestia > 0) console.log(`    nestia → tsgonest:          ${this.stats.nestia}`);
    if (this.stats.typia > 0) console.log(`    typia → tsgonest:           ${this.stats.typia}`);
    if (this.stats.classValidator > 0) console.log(`    class-validator → tsgonest: ${this.stats.classValidator}`);
    if (this.stats.classTransformer > 0) console.log(`    class-transformer → tsgonest: ${this.stats.classTransformer}`);
    if (this.stats.swagger > 0) console.log(`    @nestjs/swagger cleanup:    ${this.stats.swagger}`);
    if (this.stats.baseUrlRewrites > 0) console.log(`    baseUrl import rewrites:    ${this.stats.baseUrlRewrites}`);
    console.log(`    total:                      ${this.totalTransforms}`);
    console.log(`    files changed:              ${this.filesChanged.size}`);

    if (this.configFileGenerated) {
      console.log(`\n  Generated: tsgonest.config.ts`);
    }
    if (this.tsconfigModified) {
      console.log(`  Modified: tsconfig.json (removed baseUrl/plugins)`);
    }

    // TODOs
    const todos = this.todos;
    if (todos.length > 0) {
      console.log(`\n  ${YELLOW}Manual TODOs (${todos.length}):${RESET}`);
      for (const item of todos) {
        const loc = item.line ? `:${item.line}` : "";
        console.log(`    ${rel(item.file)}${loc}`);
        console.log(`      ${item.message}`);
      }
    }

    // Warnings
    const warnings = this.warnings;
    if (warnings.length > 0) {
      console.log(`\n  ${YELLOW}Warnings (${warnings.length}):${RESET}`);
      for (const item of warnings) {
        const loc = item.line ? `:${item.line}` : "";
        console.log(`    ${rel(item.file)}${loc}: ${item.message}`);
      }
    }
  }

  /** Generate markdown report content. */
  toMarkdown(cwd: string): string {
    const rel = (filePath: string) => relative(cwd, filePath);
    const lines: string[] = [];

    lines.push("# tsgonest Migration Report");
    lines.push("");
    lines.push(`Generated by \`tsgonest migrate --apply\` on ${new Date().toISOString().slice(0, 10)}`);
    lines.push("");

    // Summary
    lines.push("## Summary");
    lines.push("");
    lines.push("| Category | Transforms |");
    lines.push("| --- | --- |");
    if (this.stats.nestia > 0) lines.push(`| Nestia → tsgonest | ${this.stats.nestia} |`);
    if (this.stats.typia > 0) lines.push(`| Typia → tsgonest | ${this.stats.typia} |`);
    if (this.stats.classValidator > 0) lines.push(`| class-validator → tsgonest | ${this.stats.classValidator} |`);
    if (this.stats.classTransformer > 0) lines.push(`| class-transformer → tsgonest | ${this.stats.classTransformer} |`);
    if (this.stats.swagger > 0) lines.push(`| @nestjs/swagger cleanup | ${this.stats.swagger} |`);
    if (this.stats.baseUrlRewrites > 0) lines.push(`| baseUrl import rewrites | ${this.stats.baseUrlRewrites} |`);
    lines.push(`| **Total** | **${this.totalTransforms}** |`);
    lines.push(`| Files changed | ${this.filesChanged.size} |`);
    lines.push("");

    // Auto-generated files
    if (this.configFileGenerated || this.tsconfigModified) {
      lines.push("## Auto-generated Changes");
      lines.push("");
      if (this.configFileGenerated) {
        lines.push("- Created `tsgonest.config.ts` with controllers, transforms, and OpenAPI settings");
        if (this.detectedSecuritySchemes.size > 0) {
          const schemes = Array.from(this.detectedSecuritySchemes.keys()).join(", ");
          lines.push(`  - Includes auto-detected security schemes: ${schemes}`);
        }
      }
      if (this.tsconfigModified) {
        lines.push("- Modified `tsconfig.json` (removed `baseUrl` and/or compiler plugins)");
      }
      lines.push("");
    }

    // Package.json changes
    const pkgChanges = this.packageJsonChanges;
    const hasPkgChanges =
      pkgChanges.removedDeps.length > 0 ||
      pkgChanges.addedDeps.length > 0 ||
      pkgChanges.updatedScripts.length > 0 ||
      pkgChanges.removedConfigFiles.length > 0;

    if (hasPkgChanges) {
      lines.push("## Package Changes");
      lines.push("");
      if (pkgChanges.removedDeps.length > 0) {
        lines.push("**Removed dependencies:**");
        for (const dep of pkgChanges.removedDeps) {
          lines.push(`- \`${dep}\``);
        }
        lines.push("");
      }
      if (pkgChanges.addedDeps.length > 0) {
        lines.push("**Added dependencies:**");
        for (const dep of pkgChanges.addedDeps) {
          lines.push(`- \`${dep}\``);
        }
        lines.push("");
      }
      if (pkgChanges.updatedScripts.length > 0) {
        lines.push("**Updated scripts:**");
        for (const script of pkgChanges.updatedScripts) {
          lines.push(`- \`${script}\``);
        }
        lines.push("");
      }
      if (pkgChanges.removedConfigFiles.length > 0) {
        lines.push("**Removed config files:**");
        for (const file of pkgChanges.removedConfigFiles) {
          lines.push(`- \`${file}\``);
        }
        lines.push("");
      }
    }

    // TODOs
    const todos = this.todos;
    if (todos.length > 0) {
      lines.push("## Manual TODOs");
      lines.push("");
      lines.push("These items need manual review/action:");
      lines.push("");
      for (const item of todos) {
        const loc = item.line ? `:${item.line}` : "";
        lines.push(`- [ ] \`${rel(item.file)}${loc}\` — ${item.message}`);
      }
      lines.push("");
    }

    // Warnings
    const warnings = this.warnings;
    if (warnings.length > 0) {
      lines.push("## Warnings");
      lines.push("");
      for (const item of warnings) {
        const loc = item.line ? `:${item.line}` : "";
        lines.push(`- \`${rel(item.file)}${loc}\` — ${item.message}`);
      }
      lines.push("");
    }

    // Next steps
    lines.push("## Next Steps");
    lines.push("");
    lines.push("1. Review all changes and TODOs above");
    lines.push("2. Run your package manager to sync dependencies:");
    lines.push("   ```bash");
    lines.push("   npm install  # or: pnpm install / yarn install");
    lines.push("   ```");
    lines.push("3. If you had `TsgonestValidationPipe`/`TsgonestFastInterceptor` in `main.ts`, remove them (no longer needed)");
    lines.push("4. Run tests to verify correctness");
    lines.push("5. Build and verify: `npx tsgonest build`");
    lines.push("");

    return lines.join("\n");
  }
}
