package watcher

// Edge-case tests for the watcher. These exercise scenarios uncovered by the
// May 2026 dev-mode audit:
//
//   D. Renaming a watched root silently stops events (no error, no recovery).
//   E. Atomically populating a new subdirectory races against addRecursive,
//      so some files inside don't trigger events.
//   Leak. AfterFunc/fsnotify goroutines surviving start/stop cycles.
//
// Tests marked KnownIssue are documented bugs that pass against the broken
// behavior. When a fix lands, these tests should be flipped to assert correctness.

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

// goroutineCount returns the current number of goroutines after a brief
// stabilization delay. Useful for leak assertions that should ignore
// short-lived goroutines spawned by the test harness itself.
func goroutineCount() int {
	// Two GCs flush goroutines that exited but haven't been reaped yet.
	runtime.GC()
	runtime.GC()
	time.Sleep(50 * time.Millisecond)
	return runtime.NumGoroutine()
}

// drainEvents collects all events delivered within the timeout. Used by tests
// that want to assert on what happened instead of just first-event-wins.
func drainEvents(ch <-chan []Event, timeout time.Duration) []Event {
	var all []Event
	deadline := time.After(timeout)
	for {
		select {
		case batch := <-ch:
			all = append(all, batch...)
		case <-deadline:
			return all
		}
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// D. Watched-root rename
// ─────────────────────────────────────────────────────────────────────────────

// TestWatch_RootRename_SilentlyStopsEvents_KnownIssue documents that renaming
// the watched root makes fsnotify silently drop events. There is no logic in
// addPending or watchFsnotify to re-add the root or surface an error to the
// caller. A `tsgonest dev` user who runs `mv src src.bak && mv staging src`
// gets no rebuilds until restart.
//
// Expected fix: detect Remove/Rename on a watched root (or any directory we
// added recursively), then either (a) print a clear error and bail out of the
// fsnotify loop so the caller can retry, or (b) re-walk and re-add the root
// when the new path appears.
func TestWatch_RootRename_SilentlyStopsEvents_KnownIssue(t *testing.T) {
	parent := t.TempDir()
	src := filepath.Join(parent, "src")
	if err := os.Mkdir(src, 0755); err != nil {
		t.Fatal(err)
	}
	os.WriteFile(filepath.Join(src, "app.ts"), []byte("const a = 1;"), 0644)

	got := make(chan []Event, 16)
	w := New([]string{src}, []string{".ts"}, 50*time.Millisecond, func(events []Event) {
		got <- events
	})
	go w.Watch()
	defer w.Stop()
	time.Sleep(200 * time.Millisecond)

	// Sanity: a normal write triggers an event.
	os.WriteFile(filepath.Join(src, "app.ts"), []byte("const a = 2;"), 0644)
	select {
	case <-got:
		// good
	case <-time.After(2 * time.Second):
		t.Fatal("baseline write was not detected; test setup is broken")
	}

	// Rename the watched root out from under the watcher.
	renamed := filepath.Join(parent, "src.bak")
	if err := os.Rename(src, renamed); err != nil {
		t.Fatal(err)
	}

	// Now create the original path again and write a file inside.
	if err := os.Mkdir(src, 0755); err != nil {
		t.Fatal(err)
	}
	os.WriteFile(filepath.Join(src, "app.ts"), []byte("const a = 3;"), 0644)

	// Drain anything that arrives in the next second.
	events := drainEvents(got, 1*time.Second)

	// Today, the watcher does not re-attach to the new src/. We expect zero
	// post-rename events. When the bug is fixed, this assertion should be
	// flipped to expect at least one event for the new app.ts.
	for _, ev := range events {
		if ev.Path == filepath.Join(src, "app.ts") {
			t.Logf("FIXED: post-rename write was detected (%v) — flip this assertion", ev)
			return
		}
	}
	// Still broken — log so the test is observable but not failing CI.
	t.Logf("KNOWN ISSUE: %d events received post-rename, none for the recreated app.ts", len(events))
}

// ─────────────────────────────────────────────────────────────────────────────
// E. Atomically populated subdirectory
// ─────────────────────────────────────────────────────────────────────────────

// TestWatch_AtomicSubdirPopulation_FilesCanBeMissed_KnownIssue exercises the
// `git checkout`/`git pull` scenario: a fully-populated directory is renamed
// into the watch root in one syscall. fsnotify reports a Create on the
// directory; the watcher does addRecursive to attach to the new dir, but the
// files already inside it are not re-walked, so their Create events were never
// generated by the kernel and the recursive add doesn't synthesize them.
//
// The test renames a pre-populated directory into place, sleeps, then writes a
// new file inside the dir. If the original files' creates are not delivered,
// only the post-add write event arrives. We assert that this asymmetry exists,
// to lock in the bug. Fix: after addRecursive succeeds, walk the dir and emit
// synthetic Create events for files matching the watched extensions.
func TestWatch_AtomicSubdirPopulation_FilesCanBeMissed_KnownIssue(t *testing.T) {
	root := t.TempDir()

	// Build a populated dir outside the watch path.
	staging := filepath.Join(t.TempDir(), "package")
	if err := os.MkdirAll(staging, 0755); err != nil {
		t.Fatal(err)
	}
	for i := range 5 {
		path := filepath.Join(staging, fmt.Sprintf("file%d.ts", i))
		if err := os.WriteFile(path, []byte("export {}"), 0644); err != nil {
			t.Fatal(err)
		}
	}

	got := make(chan []Event, 64)
	w := New([]string{root}, []string{".ts"}, 50*time.Millisecond, func(events []Event) {
		got <- events
	})
	go w.Watch()
	defer w.Stop()
	time.Sleep(200 * time.Millisecond)

	// Atomically move the populated dir into the watch root.
	dest := filepath.Join(root, "package")
	if err := os.Rename(staging, dest); err != nil {
		t.Skipf("cross-device rename not allowed in temp setup: %v", err)
	}

	// Wait long enough for fsnotify Create + addRecursive + debounce.
	time.Sleep(400 * time.Millisecond)

	beforeNewWrite := drainEvents(got, 200*time.Millisecond)
	preexistingDetected := 0
	for _, ev := range beforeNewWrite {
		base := filepath.Base(ev.Path)
		if base == "file0.ts" || base == "file1.ts" || base == "file2.ts" || base == "file3.ts" || base == "file4.ts" {
			preexistingDetected++
		}
	}

	// Now write a new file in the swapped-in dir. addRecursive must have
	// completed by now, so this Create should be delivered.
	newFile := filepath.Join(dest, "after.ts")
	os.WriteFile(newFile, []byte("export const a = 1;"), 0644)
	afterEvents := drainEvents(got, 1*time.Second)
	postWriteDetected := false
	for _, ev := range afterEvents {
		if filepath.Base(ev.Path) == "after.ts" {
			postWriteDetected = true
		}
	}

	if !postWriteDetected {
		t.Fatal("fsnotify did not detect the post-rename write — addRecursive itself is broken")
	}

	// The bug: pre-existing files were typically not delivered as events.
	// Some platforms (Linux inotify) may deliver them; macOS kqueue typically
	// does not. We log instead of asserting hard so the test stays portable.
	t.Logf("preexisting files reported as events: %d/5 (post-rename write detected: %v)",
		preexistingDetected, postWriteDetected)
	if preexistingDetected == 5 {
		t.Logf("FIXED on this platform — flip to assertion when fix lands")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Goroutine and timer leaks
// ─────────────────────────────────────────────────────────────────────────────

// TestWatch_GoroutineCountStableAcrossRestarts repeatedly creates and stops
// watchers, asserting that the goroutine count returns to baseline. Catches
// regressions where Stop() forgets to release the fsnotify backend goroutine,
// or where pending AfterFunc timers never get reaped.
func TestWatch_GoroutineCountStableAcrossRestarts(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "app.ts"), []byte("x"), 0644)

	baseline := goroutineCount()

	const iterations = 50
	for range iterations {
		w := New([]string{dir}, []string{".ts"}, 20*time.Millisecond, func(events []Event) {})
		go w.Watch()
		// Let the fsnotify backend spin up.
		time.Sleep(20 * time.Millisecond)
		w.Stop()
		// Brief gap so Stop's stopCh propagates before the next iter.
		time.Sleep(20 * time.Millisecond)
	}

	final := goroutineCount()
	delta := final - baseline

	// Allow some slack for Go runtime housekeeping. Anything more than ~5 is
	// almost certainly a leak.
	if delta > 5 {
		t.Errorf("goroutine count grew by %d after %d watcher cycles (baseline=%d, final=%d)",
			delta, iterations, baseline, final)
	} else {
		t.Logf("goroutine delta after %d cycles: %d (baseline=%d, final=%d)",
			iterations, delta, baseline, final)
	}
}

// TestWatch_AfterFuncTimerNotLeakedOnRapidEvents fires many file changes in
// quick succession and asserts that the timer goroutine count stays bounded.
// The watcher's debounce uses a single replaceable timer (addPending stops the
// previous before launching a new), so worst case is 1 outstanding timer —
// not N.
func TestWatch_AfterFuncTimerNotLeakedOnRapidEvents(t *testing.T) {
	dir := t.TempDir()

	// Slow consumer: only counts events. Doesn't matter for the timer test.
	var fired int32
	w := New([]string{dir}, []string{".ts"}, 100*time.Millisecond, func(events []Event) {
		atomic.AddInt32(&fired, int32(len(events)))
	})
	go w.Watch()
	defer w.Stop()
	time.Sleep(100 * time.Millisecond)

	baseline := goroutineCount()

	// Burst 200 file writes. Each addPending call stops the existing timer
	// and creates a new one. Stop() on a fired timer is a no-op, so the
	// already-fired timer's goroutine completes naturally; pending timers
	// get cancelled.
	for i := range 200 {
		os.WriteFile(filepath.Join(dir, fmt.Sprintf("f%d.ts", i)), []byte("x"), 0644)
	}

	// Let everything settle.
	time.Sleep(500 * time.Millisecond)

	peak := goroutineCount()
	delta := peak - baseline
	if delta > 3 {
		t.Errorf("goroutine delta during burst was %d — timer goroutines may be leaking", delta)
	} else {
		t.Logf("goroutine delta during 200-file burst: %d (baseline=%d, peak=%d, fired=%d)",
			delta, baseline, peak, atomic.LoadInt32(&fired))
	}
}

// TestWatch_StopUnblocksOnChangeCallbackInFlight verifies that Stop() can be
// called while a debounce timer is mid-callback, and that the callback's
// onChange is allowed to complete without deadlocking the caller.
func TestWatch_StopUnblocksOnChangeCallbackInFlight(t *testing.T) {
	dir := t.TempDir()

	callbackEntered := make(chan struct{})
	callbackCanReturn := make(chan struct{})

	w := New([]string{dir}, []string{".ts"}, 30*time.Millisecond, func(events []Event) {
		// Block inside the callback to simulate a slow consumer.
		select {
		case callbackEntered <- struct{}{}:
		default:
		}
		<-callbackCanReturn
	})
	go w.Watch()
	defer close(callbackCanReturn)
	time.Sleep(100 * time.Millisecond)

	// Trigger one event.
	os.WriteFile(filepath.Join(dir, "a.ts"), []byte("x"), 0644)

	select {
	case <-callbackEntered:
		// good
	case <-time.After(2 * time.Second):
		t.Fatal("debounce callback never fired")
	}

	// Stop the watcher while the callback is blocked. Stop should not deadlock.
	stopped := make(chan struct{})
	go func() {
		w.Stop()
		close(stopped)
	}()

	select {
	case <-stopped:
		// good — Stop didn't wait for the callback
	case <-time.After(1 * time.Second):
		t.Fatal("Stop deadlocked on in-flight callback (it shouldn't synchronize with the user's onChange)")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Polling fallback edge cases
// ─────────────────────────────────────────────────────────────────────────────

// TestWatch_PollingDetectsContentEqualSizeRewrite verifies the polling fallback
// catches "rewrite the file with same length but different content" — which
// requires mtime to bump (size alone is unchanged). This is the common path for
// editing a single character.
func TestWatch_PollingDetectsContentEqualSizeRewrite(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "a.ts")
	os.WriteFile(f, []byte("export const x=1;"), 0644)

	w := &Watcher{
		dirs:         []string{dir},
		extensions:   []string{".ts"},
		debounce:     20 * time.Millisecond,
		pollInterval: 30 * time.Millisecond,
	}

	old := w.buildSnapshot()

	// Sleep long enough for mtime to differ.
	time.Sleep(50 * time.Millisecond)
	os.WriteFile(f, []byte("export const x=2;"), 0644)
	new := w.buildSnapshot()

	events := w.diff(old, new)
	if len(events) != 1 || events[0].Op != "write" {
		t.Errorf("expected 1 write event, got %v", events)
	}
}

// TestWatch_PollingMissesIdenticalSizeIdenticalMtimeRewrite locks in the
// known limitation that polling cannot detect a same-size + same-mtime rewrite
// (extremely rare, requires deliberately-frozen mtimes — possible with `touch
// -t` or filesystems with low mtime resolution like FAT32). Documenting it.
func TestWatch_PollingMissesIdenticalSizeIdenticalMtimeRewrite(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "a.ts")
	if err := os.WriteFile(f, []byte("aaa"), 0644); err != nil {
		t.Fatal(err)
	}

	w := &Watcher{
		dirs:         []string{dir},
		extensions:   []string{".ts"},
		debounce:     20 * time.Millisecond,
		pollInterval: 30 * time.Millisecond,
	}

	// Capture mtime so we can re-stamp the rewrite.
	info, err := os.Stat(f)
	if err != nil {
		t.Fatal(err)
	}
	old := w.buildSnapshot()

	// Rewrite with same length, then force mtime back to the original.
	if err := os.WriteFile(f, []byte("bbb"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chtimes(f, info.ModTime(), info.ModTime()); err != nil {
		t.Fatal(err)
	}

	new := w.buildSnapshot()
	events := w.diff(old, new)
	if len(events) != 0 {
		t.Logf("FIXED on this platform: polling now catches frozen-mtime rewrites: %v", events)
	} else {
		t.Logf("KNOWN LIMITATION: polling cannot detect same-size same-mtime rewrites")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// shouldSkipPath edge cases
// ─────────────────────────────────────────────────────────────────────────────

// TestShouldSkipPath_CaseSensitive_KnownIssue documents that shouldSkipPath
// uses case-sensitive Contains. On Windows (case-insensitive filesystem), a
// path containing "Node_Modules" is not skipped. Fix: strings.EqualFold or
// a normalized comparison.
func TestShouldSkipPath_CaseSensitive_KnownIssue(t *testing.T) {
	cases := []struct {
		path        string
		shouldSkip  bool
		description string
	}{
		{filepath.Join("project", "node_modules", "foo"), true, "lowercase always skipped"},
		{filepath.Join("project", "Node_Modules", "foo"), true, "Windows-style mixed-case (currently NOT skipped — bug)"},
		{filepath.Join("project", "NODE_MODULES", "foo"), true, "uppercase (currently NOT skipped — bug)"},
		{filepath.Join("project", ".git", "objects"), true, ".git always skipped"},
		{filepath.Join("project", "src", "node_modulesFake"), false, "should NOT skip lookalikes"},
	}
	for _, c := range cases {
		got := shouldSkipPath(c.path)
		if got != c.shouldSkip {
			t.Logf("shouldSkipPath(%q) = %v, want %v — %s", c.path, got, c.shouldSkip, c.description)
		}
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Stress: many concurrent file events
// ─────────────────────────────────────────────────────────────────────────────

// TestWatch_BurstWritesNoDataRace runs the watcher under concurrent writes to
// `go test -race` for a few hundred file events. Catches data races in the
// shared `pending` slice.
func TestWatch_BurstWritesNoDataRace(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping stress test in -short mode")
	}
	dir := t.TempDir()

	w := New([]string{dir}, []string{".ts"}, 30*time.Millisecond, func(events []Event) {})
	go w.Watch()
	defer w.Stop()
	time.Sleep(100 * time.Millisecond)

	var wg sync.WaitGroup
	for w := range 8 {
		wg.Add(1)
		go func(worker int) {
			defer wg.Done()
			for i := range 50 {
				path := filepath.Join(dir, fmt.Sprintf("w%d_f%d.ts", worker, i))
				_ = os.WriteFile(path, []byte("x"), 0644)
			}
		}(w)
	}
	wg.Wait()
	time.Sleep(200 * time.Millisecond)
}
