package sdkgen

// generateClient generates the client.ts file with core HTTP infrastructure types and the request function.
// SSEConnection and buildFormData are now in separate files (sse.ts, form-data.ts) for tree-shaking.
func generateClient() string {
	return `// Auto-generated by tsgonest sdk — do not edit

export interface SDKError {
  status: number;
  message: string;
  body?: unknown;
}

export interface RequestContext {
  method: string;
  path: string;
  url: string;
}

export type SDKResult<T> = { data: T; error: null; response: Response } | { data: null; error: SDKError; response: Response };

export type Fetcher = (url: string, init: RequestInit) => Promise<Response>;

export type HeadersInit = Record<string, string> | (() => Record<string, string> | Promise<Record<string, string>>);

export interface ClientConfig {
  baseUrl: string;
  headers?: HeadersInit;
  fetcher?: Fetcher;
  onRequest?: (url: string, init: RequestInit) => RequestInit | Promise<RequestInit>;
  timeout?: number;
  throwOnError?: boolean;
  onResponse?: (response: Response, context: RequestContext) => Response | void | Promise<Response | void>;
  onError?: (error: SDKError, context: RequestContext) => SDKError | void | Promise<SDKError | void>;
}

export function extractErrorMessage(body: unknown, fallback: string): string {
  if (body != null && typeof body === 'object') {
    const b = body as Record<string, unknown>;
    if (typeof b.message === 'string') return b.message;
    if (Array.isArray(b.message) && b.message.length > 0 && typeof b.message[0] === 'string') return b.message[0];
    if (b.error != null && typeof b.error === 'object') {
      const nested = b.error as Record<string, unknown>;
      if (typeof nested.message === 'string') return nested.message;
    }
    if (typeof b.error === 'string') return b.error;
  }
  return fallback;
}

export type RequestFn = <T>(
  method: string,
  path: string,
  options?: {
    params?: Record<string, string>;
    query?: Record<string, unknown>;
    body?: unknown;
    headers?: Record<string, string>;
    signal?: AbortSignal;
    contentType?: string;
    responseType?: 'json' | 'blob' | 'text' | 'stream' | 'sse' | 'sse-raw';
  },
) => Promise<SDKResult<T>>;

export function createRequestFn(config: ClientConfig): RequestFn {
  const fetcher = config.fetcher ?? fetch;

  return async <T>(
    method: string,
    path: string,
    options?: {
      params?: Record<string, string>;
      query?: Record<string, unknown>;
      body?: unknown;
      headers?: Record<string, string>;
      signal?: AbortSignal;
      contentType?: string;
      responseType?: 'json' | 'blob' | 'text' | 'stream' | 'sse' | 'sse-raw';
    },
  ): Promise<SDKResult<T>> => {
    // Interpolate path params
    let url = path;
    if (options?.params) {
      for (const [key, value] of Object.entries(options.params)) {
        url = url.replace(` + "`{${key}}`" + `, encodeURIComponent(value));
      }
    }

    // Build query string
    if (options?.query) {
      const searchParams = new URLSearchParams();
      for (const [key, value] of Object.entries(options.query)) {
        if (value === undefined || value === null) continue;
        if (Array.isArray(value)) {
          for (const item of value) {
            searchParams.append(key, String(item));
          }
        } else {
          searchParams.set(key, String(value));
        }
      }
      const qs = searchParams.toString();
      if (qs) url += ` + "`?${qs}`" + `;
    }

    const fullUrl = config.baseUrl.replace(/\/$/, '') + url;

    // Build request context for hooks
    const context: RequestContext = { method, path, url: fullUrl };

    // Resolve headers
    let baseHeaders: Record<string, string> = {};
    if (config.headers) {
      if (typeof config.headers === 'function') {
        baseHeaders = await config.headers();
      } else {
        baseHeaders = config.headers;
      }
    }

    const allHeaders: Record<string, string> = {
      ...baseHeaders,
      ...options?.headers,
    };

    // Build request init
    let init: RequestInit = {
      method,
      headers: allHeaders,
      signal: options?.signal,
    };

    if (options?.body !== undefined) {
      const contentType = options?.contentType ?? 'application/json';
      if (options.body instanceof FormData) {
        // Let the browser set the Content-Type with boundary
        init.body = options.body;
      } else if (contentType === 'application/json') {
        init.body = JSON.stringify(options.body);
        allHeaders['Content-Type'] = 'application/json';
        init.headers = allHeaders;
      } else {
        init.body = String(options.body);
        allHeaders['Content-Type'] = contentType;
        init.headers = allHeaders;
      }
    }

    // onRequest hook
    if (config.onRequest) {
      init = await config.onRequest(fullUrl, init);
    }

    // Apply timeout
    if (config.timeout != null) {
      const timeoutSignal = AbortSignal.timeout(config.timeout);
      init.signal = init.signal ? AbortSignal.any([init.signal, timeoutSignal]) : timeoutSignal;
    }

    let response = await fetcher(fullUrl, init);

    // onResponse hook (fires on ALL responses)
    if (config.onResponse) {
      const replaced = await config.onResponse(response, context);
      if (replaced) response = replaced;
    }

    if (!response.ok) {
      let errorBody: unknown;
      try {
        errorBody = await response.json();
      } catch {
        errorBody = await response.text().catch(() => undefined);
      }
      let error: SDKError = {
        status: response.status,
        message: extractErrorMessage(errorBody, response.statusText),
        body: errorBody,
      };
      // onError hook
      if (config.onError) {
        const replaced = await config.onError(error, context);
        if (replaced) error = replaced;
      }
      // throwOnError
      if (config.throwOnError) {
        throw error;
      }
      return { data: null, error, response };
    }

    // 204 No Content
    if (response.status === 204) {
      return { data: undefined as T, error: null, response };
    }

    // Response type hint from codegen
    const respType = options?.responseType ?? 'json';

    if (respType === 'blob') {
      const data = await response.blob() as T;
      return { data, error: null, response };
    }

    if (respType === 'stream') {
      return { data: response.body as T, error: null, response };
    }

    if (respType === 'sse' || respType === 'sse-raw') {
      // SSE handling is done by the controller via SSEConnection from sse.ts
      return { data: response as unknown as T, error: null, response };
    }

    if (respType === 'text') {
      const data = await response.text() as T;
      return { data, error: null, response };
    }

    // Default: parse based on content-type header
    const contentTypeHeader = response.headers.get('content-type') ?? '';
    if (contentTypeHeader.includes('application/json')) {
      const data = await response.json() as T;
      return { data, error: null, response };
    }

    const text = await response.text();
    return { data: text as T, error: null, response };
  };
}
`
}
