package sdkgen

// generateFormData generates the form-data.ts file with the buildFormData utility.
// Separated from client.ts for tree-shaking: only included when a controller uses multipart/form-data.
func generateFormData() string {
	return `// Auto-generated by tsgonest sdk — do not edit

export type FormDataValue = string | number | boolean | File | Blob | Date | null | undefined;
export type FormDataCompatible = Record<string, FormDataValue | FormDataValue[]>;

export function buildFormData<T extends { [K in keyof T]: FormDataValue | FormDataValue[] }>(data: T): FormData {
  const formData = new FormData();

  function appendValue(key: string, value: unknown) {
    if (value instanceof File) {
      formData.append(key, value, value.name);
      return;
    }
    if (value instanceof Blob) {
      formData.append(key, value, 'blob');
      return;
    }
    if (value instanceof Date) {
      formData.append(key, value.toISOString());
      return;
    }
    if (typeof value === 'number' || typeof value === 'boolean') {
      formData.append(key, String(value));
      return;
    }
    if (typeof value === 'string') {
      formData.append(key, value);
      return;
    }
  }

  if (data && typeof data === 'object') {
    for (const [key, value] of Object.entries(data as Record<string, unknown>)) {
      if (value === undefined || value === null) continue;
      if (Array.isArray(value)) {
        for (const item of value) {
          if (item === undefined || item === null) continue;
          appendValue(key, item);
        }
      } else {
        appendValue(key, value);
      }
    }
  }

  return formData;
}
`
}
