package sdkgen

import (
	"encoding/json"
	"fmt"
	"strings"
)

// generateIndex generates the root index.ts that re-exports everything.
func generateIndex(versions []VersionGroup) string {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by tsgonest sdk — do not edit\n\n")

	// Re-export client types and factory
	sb.WriteString("export { createRequestFn } from './client';\n")
	sb.WriteString("export type { ClientConfig, SDKResult, SDKError, Fetcher, RequestFn, HeadersInit } from './client';\n")

	// Re-export all types
	sb.WriteString("export * from './types';\n")
	sb.WriteString("\n")

	// Re-export controller factories (only unversioned to avoid name collisions)
	for _, ver := range versions {
		if ver.Version != "" {
			continue // versioned controllers imported via @app/sdk/v1/orders
		}
		for _, ctrl := range ver.Controllers {
			dirPath := controllerImportPath(ver.Version, ctrl.Name)
			factoryName := controllerFactoryName(ctrl.Name)
			ifaceName := controllerInterfaceName(ctrl.Name)
			sb.WriteString(fmt.Sprintf("export { %s } from './%s';\n", factoryName, dirPath))
			sb.WriteString(fmt.Sprintf("export type { %s } from './%s';\n", ifaceName, dirPath))
		}
	}

	sb.WriteString("\n")

	// Generate createClient function that returns all controllers
	sb.WriteString("import { createRequestFn as _createRequestFn } from './client';\n")
	sb.WriteString("import type { ClientConfig as _ClientConfig } from './client';\n")

	// Import all controller factories
	for _, ver := range versions {
		for _, ctrl := range ver.Controllers {
			dirPath := controllerImportPath(ver.Version, ctrl.Name)
			factoryName := controllerFactoryName(ctrl.Name)
			importAlias := factoryImportAlias(ver.Version, factoryName)
			sb.WriteString(fmt.Sprintf("import { %s as %s } from './%s';\n", factoryName, importAlias, dirPath))
		}
	}

	sb.WriteString("\n")

	// Build the createClient return type
	sb.WriteString("export function createClient(config: _ClientConfig) {\n")
	sb.WriteString("  const request = _createRequestFn(config);\n")
	sb.WriteString("  return {\n")

	for _, ver := range versions {
		if ver.Version == "" {
			// Unversioned: flat
			for _, ctrl := range ver.Controllers {
				propName := controllerPropertyName(ctrl.Name)
				importAlias := factoryImportAlias(ver.Version, controllerFactoryName(ctrl.Name))
				sb.WriteString(fmt.Sprintf("    %s: %s(request),\n", propName, importAlias))
			}
		} else {
			// Versioned: nested under version key
			sb.WriteString(fmt.Sprintf("    %s: {\n", ver.Version))
			for _, ctrl := range ver.Controllers {
				propName := controllerPropertyName(ctrl.Name)
				importAlias := factoryImportAlias(ver.Version, controllerFactoryName(ctrl.Name))
				sb.WriteString(fmt.Sprintf("      %s: %s(request),\n", propName, importAlias))
			}
			sb.WriteString("    },\n")
		}
	}

	sb.WriteString("  };\n")
	sb.WriteString("}\n")

	return sb.String()
}

// generatePackageJSON generates a package.json with exports map for tree-shaking.
func generatePackageJSON(versions []VersionGroup) string {
	exports := map[string]string{
		".":        "./index.ts",
		"./client": "./client.ts",
		"./types":  "./types.ts",
	}

	for _, ver := range versions {
		for _, ctrl := range ver.Controllers {
			dirPath := controllerImportPath(ver.Version, ctrl.Name)
			exports["./"+dirPath] = "./" + dirPath + "/index.ts"
		}
	}

	pkg := map[string]any{
		"name":    "@app/sdk",
		"version": "0.0.0",
		"private": true,
		"exports": exports,
	}

	data, _ := json.MarshalIndent(pkg, "", "  ")
	return string(data) + "\n"
}

// controllerImportPath returns the import path for a controller from the SDK root.
// e.g., "v1/orders" or "orders"
func controllerImportPath(version, controllerName string) string {
	dirName := controllerDirName(controllerName)
	if version != "" {
		return version + "/" + dirName
	}
	return dirName
}

// controllerPropertyName returns the property name on the client object.
// e.g., "OrdersController" → "orders"
func controllerPropertyName(name string) string {
	base := strings.TrimSuffix(name, "Controller")
	if base == "" {
		return "default"
	}
	return strings.ToLower(base[:1]) + base[1:]
}

// factoryImportAlias returns a unique import alias for a versioned factory.
func factoryImportAlias(version, factoryName string) string {
	if version == "" {
		return "_" + factoryName
	}
	return "_" + version + "_" + factoryName
}
