package sdkgen

import (
	"sort"
	"strings"
)

// generateSharedTypes generates the types.ts file with all component schemas.
func generateSharedTypes(schemas map[string]*SchemaNode) string {
	if len(schemas) == 0 {
		return "// No schemas defined\nexport {};\n"
	}

	var sb strings.Builder
	sb.WriteString("// Auto-generated by tsgonest sdk — do not edit\n\n")

	// Sort schema names for stable output
	var names []string
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	visited := make(map[string]bool)
	for i, name := range names {
		if i > 0 {
			sb.WriteString("\n")
		}
		sb.WriteString(GenerateInterface(name, schemas[name], visited))
	}

	return sb.String()
}
