
// Code generated by tools/gen_shims. DO NOT EDIT.

package incremental

import "github.com/microsoft/typescript-go/internal/compiler"
import "github.com/microsoft/typescript-go/internal/core"
import "github.com/microsoft/typescript-go/internal/execute/incremental"
import "github.com/microsoft/typescript-go/internal/tsoptions"
import "time"
import _ "unsafe"

type BuildInfo = incremental.BuildInfo
type BuildInfoDiagnostic = incremental.BuildInfoDiagnostic
type BuildInfoDiagnosticsOfFile = incremental.BuildInfoDiagnosticsOfFile
type BuildInfoEmitSignature = incremental.BuildInfoEmitSignature
type BuildInfoFileId = incremental.BuildInfoFileId
type BuildInfoFileIdListId = incremental.BuildInfoFileIdListId
type BuildInfoFileInfo = incremental.BuildInfoFileInfo
type BuildInfoFilePendingEmit = incremental.BuildInfoFilePendingEmit
type BuildInfoReader = incremental.BuildInfoReader
type BuildInfoReferenceMapEntry = incremental.BuildInfoReferenceMapEntry
type BuildInfoResolvedRoot = incremental.BuildInfoResolvedRoot
type BuildInfoRoot = incremental.BuildInfoRoot
type BuildInfoRootInfoReader = incremental.BuildInfoRootInfoReader
type BuildInfoSemanticDiagnostic = incremental.BuildInfoSemanticDiagnostic
//go:linkname ComputeHash github.com/microsoft/typescript-go/internal/execute/incremental.ComputeHash
func ComputeHash(text string, hashWithText bool) string
//go:linkname CreateHost github.com/microsoft/typescript-go/internal/execute/incremental.CreateHost
func CreateHost(compilerHost compiler.CompilerHost) incremental.Host
type DiagnosticsOrBuildInfoDiagnosticsWithFileName = incremental.DiagnosticsOrBuildInfoDiagnosticsWithFileName
type FileEmitKind = incremental.FileEmitKind
const FileEmitKindAll = incremental.FileEmitKindAll
const FileEmitKindAllDts = incremental.FileEmitKindAllDts
const FileEmitKindAllDtsEmit = incremental.FileEmitKindAllDtsEmit
const FileEmitKindAllJs = incremental.FileEmitKindAllJs
const FileEmitKindDts = incremental.FileEmitKindDts
const FileEmitKindDtsEmit = incremental.FileEmitKindDtsEmit
const FileEmitKindDtsErrors = incremental.FileEmitKindDtsErrors
const FileEmitKindDtsMap = incremental.FileEmitKindDtsMap
const FileEmitKindJs = incremental.FileEmitKindJs
const FileEmitKindJsInlineMap = incremental.FileEmitKindJsInlineMap
const FileEmitKindJsMap = incremental.FileEmitKindJsMap
const FileEmitKindNone = incremental.FileEmitKindNone
type FileInfo = incremental.FileInfo
//go:linkname GetFileEmitKind github.com/microsoft/typescript-go/internal/execute/incremental.GetFileEmitKind
func GetFileEmitKind(options *core.CompilerOptions) incremental.FileEmitKind
//go:linkname GetMTime github.com/microsoft/typescript-go/internal/execute/incremental.GetMTime
func GetMTime(host compiler.CompilerHost, fileName string) time.Time
type Host = incremental.Host
//go:linkname NewBuildInfoReader github.com/microsoft/typescript-go/internal/execute/incremental.NewBuildInfoReader
func NewBuildInfoReader(host compiler.CompilerHost) incremental.BuildInfoReader
//go:linkname NewProgram github.com/microsoft/typescript-go/internal/execute/incremental.NewProgram
func NewProgram(program *compiler.Program, oldProgram *incremental.Program, host incremental.Host, testing bool) *incremental.Program
type Program = incremental.Program
//go:linkname ReadBuildInfoProgram github.com/microsoft/typescript-go/internal/execute/incremental.ReadBuildInfoProgram
func ReadBuildInfoProgram(config *tsoptions.ParsedCommandLine, reader incremental.BuildInfoReader, host compiler.CompilerHost) *incremental.Program
type SignatureUpdateKind = incremental.SignatureUpdateKind
const SignatureUpdateKindComputedDts = incremental.SignatureUpdateKindComputedDts
const SignatureUpdateKindStoredAtEmit = incremental.SignatureUpdateKindStoredAtEmit
const SignatureUpdateKindUsedVersion = incremental.SignatureUpdateKindUsedVersion
type TestingData = incremental.TestingData
