
// Code generated by tools/gen_shims. DO NOT EDIT.

package fswatch

import "github.com/microsoft/typescript-go/internal/fswatch"
import _ "unsafe"

//go:linkname AllWatchers github.com/microsoft/typescript-go/internal/fswatch.AllWatchers
func AllWatchers() []fswatch.Watcher
//go:linkname Default github.com/microsoft/typescript-go/internal/fswatch.Default
func Default() fswatch.Watcher
var ErrOverflow = fswatch.ErrOverflow
var ErrUnavailable = fswatch.ErrUnavailable
var ErrWatchTerminated = fswatch.ErrWatchTerminated
type Event = fswatch.Event
const EventDelete = fswatch.EventDelete
type EventKind = fswatch.EventKind
const EventUpdate = fswatch.EventUpdate
//go:linkname FSEvents github.com/microsoft/typescript-go/internal/fswatch.FSEvents
func FSEvents() fswatch.Watcher
//go:linkname Fanotify github.com/microsoft/typescript-go/internal/fswatch.Fanotify
func Fanotify() fswatch.Watcher
//go:linkname Inotify github.com/microsoft/typescript-go/internal/fswatch.Inotify
func Inotify() fswatch.Watcher
//go:linkname Kqueue github.com/microsoft/typescript-go/internal/fswatch.Kqueue
func Kqueue() fswatch.Watcher
type Watch = fswatch.Watch
type WatchCallback = fswatch.WatchCallback
type WatchDirectoryRequest = fswatch.WatchDirectoryRequest
type WatchOption = fswatch.WatchOption
type Watcher = fswatch.Watcher
//go:linkname Windows github.com/microsoft/typescript-go/internal/fswatch.Windows
func Windows() fswatch.Watcher
//go:linkname WithIgnore github.com/microsoft/typescript-go/internal/fswatch.WithIgnore
func WithIgnore(fn func(path string) bool) fswatch.WatchOption
//go:linkname WithRecursive github.com/microsoft/typescript-go/internal/fswatch.WithRecursive
func WithRecursive() fswatch.WatchOption
